name: 1110 On The Parkway Medi-Spa
favicon: null
layout_spectrum: 0.42744468292221427
typography_spectrum: 0.8575755367055535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b2803'
    - '#29621b'
    - '#a4cf5b'
    - '#259fd9'
    - '#0000ff'
  brandStrength: 0.5773414236027747
  lightness: 0.81840276485309
  saturation: 0.5994768980890512
  rhythmicContrast: 0.3808802056591958
purpose: []
